# Generated by Django 4.2 on 2023-06-25 18:09

from django.db import migrations
import home.oneoff_blocks
import wagtail.blocks
import wagtail.contrib.table_block.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_problem_answer_problem_identifier_problem_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='answer',
            field=wagtail.fields.StreamField([('text', wagtail.blocks.RichTextBlock(group='basic')), ('image', wagtail.images.blocks.ImageChooserBlock(group='basic', template='blocks/image.html')), ('table', wagtail.contrib.table_block.blocks.TableBlock(group='basic')), ('code', wagtail.blocks.StructBlock([('language', wagtail.blocks.CharBlock(required=False)), ('code', wagtail.blocks.TextBlock())], group='basic')), ('ImageDivider', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock())])), ('GradientDescentWidget', wagtail.blocks.StructBlock([], group='oneoff')), ('StatisticalMurderWidget', home.oneoff_blocks.StatisticalMurderWidget(group='oneoff')), ('IRTWidget', home.oneoff_blocks.IRTWidget(group='oneoff')), ('WealthEnergyWidget', home.oneoff_blocks.WealthEnergyWidget(group='oneoff'))], blank=True, null=True, use_json_field=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='question',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
    ]
