# Generated by Django 4.2 on 2024-06-26 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0003_alter_problem_answer_alter_problem_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problems', to='problems.book'),
        ),
    ]
