# Generated by Django 4.0.7 on 2022-08-29 18:35

from django.db import migrations
import home.blocks
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='header',
            field=wagtail.fields.StreamField([('ImageHeader', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())])), ('ImageDivider', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock())])), ('spacer', home.blocks.SpacerBlock())], blank=True, null=True, use_json_field=None),
        ),
        migrations.AlterField(
            model_name='series',
            name='articles',
            field=wagtail.fields.StreamField([('articles', wagtail.blocks.ListBlock(wagtail.blocks.PageChooserBlock()))], blank=True, null=True, use_json_field=True),
        ),
    ]
