# Generated by Django 4.0.5 on 2022-08-07 00:20

from django.db import migrations, models
import django.db.models.deletion
import home.blocks
import wagtail.blocks
import wagtail.contrib.table_block.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0069_log_entry_jsonfield'),
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AddField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('columns', wagtail.blocks.StructBlock([('children', wagtail.blocks.ListBlock(home.blocks.ColumnBlock)), ('margin_y', wagtail.blocks.BooleanBlock(default=False, required=False)), ('margin_x', wagtail.blocks.BooleanBlock(default=False, required=False)), ('fullscreen', wagtail.blocks.BooleanBlock(default=False, required=False))])), ('spacer', home.blocks.SpacerBlock()), ('ImageHeader', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())])), ('ImageDivider', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock())])), ('ImageCard', wagtail.blocks.StructBlock([('header', wagtail.blocks.CharBlock()), ('description', wagtail.blocks.CharBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('link', wagtail.blocks.CharBlock()), ('link_text', wagtail.blocks.CharBlock())])), ('text', wagtail.blocks.RichTextBlock()), ('image_card', wagtail.blocks.StructBlock([('header', wagtail.blocks.CharBlock()), ('description', wagtail.blocks.CharBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('link', wagtail.blocks.CharBlock()), ('link_text', wagtail.blocks.CharBlock())])), ('image', wagtail.images.blocks.ImageChooserBlock(template='blocks/image.html')), ('table', wagtail.contrib.table_block.blocks.TableBlock())], blank=True, null=True, use_json_field=None),
        ),
    ]
