# Generated by Django 4.0.5 on 2022-08-07 16:59

from django.db import migrations, models
import django.utils.timezone
import sortedm2m.fields
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_pagetag_series_article_tags_alter_homepage_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='body',
            field=wagtail.fields.StreamField([], blank=True, null=True, use_json_field=True),
        ),
        migrations.AddField(
            model_name='series',
            name='articles',
            field=sortedm2m.fields.SortedManyToManyField(help_text=None, to='home.article'),
        ),
        migrations.AddField(
            model_name='series',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='series',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
