# Generated by Django 4.0.5 on 2022-08-07 20:29

from django.db import migrations
import home.blocks
import wagtail.blocks
import wagtail.contrib.table_block.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_article_body_series_articles_series_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='header',
            field=wagtail.fields.StreamField([('ImageHeader', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())])), ('ImageDivider', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock())]))], blank=True, null=True, use_json_field=None),
        ),
        migrations.AlterField(
            model_name='article',
            name='body',
            field=wagtail.fields.StreamField([('text', wagtail.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock(template='blocks/image.html')), ('table', wagtail.contrib.table_block.blocks.TableBlock()), ('ImageHeader', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())])), ('ImageDivider', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock())]))], blank=True, null=True, use_json_field=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('AboutBlurb', wagtail.blocks.StructBlock([('tagline', wagtail.blocks.CharBlock()), ('column1_text', wagtail.blocks.RichTextBlock()), ('column2_text', wagtail.blocks.RichTextBlock()), ('page', wagtail.blocks.PageChooserBlock())])), ('JumbotronCard', wagtail.blocks.StructBlock([('page', wagtail.blocks.PageChooserBlock())])), ('CardList', wagtail.blocks.StructBlock([('pages', wagtail.blocks.ListBlock(wagtail.blocks.PageChooserBlock()))])), ('LinesList', wagtail.blocks.StructBlock([('pages', wagtail.blocks.ListBlock(wagtail.blocks.PageChooserBlock())), ('include_images', wagtail.blocks.BooleanBlock(default=True, required=False))])), ('ContactForm', home.blocks.ContactForm()), ('columns', wagtail.blocks.StructBlock([('children', wagtail.blocks.ListBlock(home.blocks.ColumnBlock)), ('margin_y', wagtail.blocks.BooleanBlock(default=False, required=False)), ('margin_x', wagtail.blocks.BooleanBlock(default=False, required=False)), ('fullscreen', wagtail.blocks.BooleanBlock(default=False, required=False))])), ('spacer', home.blocks.SpacerBlock()), ('ImageHeader', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())])), ('ImageDivider', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock())])), ('ImageCard', wagtail.blocks.StructBlock([('header', wagtail.blocks.CharBlock()), ('description', wagtail.blocks.CharBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('link', wagtail.blocks.CharBlock()), ('link_text', wagtail.blocks.CharBlock())])), ('text', wagtail.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock(template='blocks/image.html')), ('table', wagtail.contrib.table_block.blocks.TableBlock())], blank=True, null=True, use_json_field=True),
        ),
    ]
