# Generated by Django 4.0.7 on 2022-08-29 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_homepage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='description',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='series',
            name='name',
            field=models.CharField(default='test', max_length=256),
            preserve_default=False,
        ),
    ]
