# Generated by Django 4.2 on 2024-06-26 15:28

from django.db import migrations, models
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_article_garden_status_homepage_garden_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='unlisted',
            field=models.BooleanField(default=False, help_text='If unlisted, the article will be publically accessible, and indexable by search engine, but will not show up in search, or in the list of articles on the homepage'),
        ),
        migrations.AlterField(
            model_name='article',
            name='garden_status',
            field=models.CharField(choices=[('na', 'None'), ('seedling', '🌱 Seedling: For rough and early ideas'), ('budding', '🌿 Budding: For work that has been cleaned up and clarified'), ('evergreen', "🌳 Evergreen: For work that's reasonably complete, but might still receive updates.")], default='na', help_text='If set, the page will show up in the garden section of the site.', max_length=10),
        ),
        migrations.AlterField(
            model_name='article',
            name='is_project',
            field=models.BooleanField(default=False, help_text='Will show up in projects section'),
        ),
        migrations.AlterField(
            model_name='article',
            name='unlisted',
            field=models.BooleanField(default=False, help_text='If unlisted, the article will be publically accessible, and indexable by search engine, but will not show up in search, or in the list of articles on the homepage'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='garden_status',
            field=models.CharField(choices=[('na', 'None'), ('seedling', '🌱 Seedling: For rough and early ideas'), ('budding', '🌿 Budding: For work that has been cleaned up and clarified'), ('evergreen', "🌳 Evergreen: For work that's reasonably complete, but might still receive updates.")], default='na', help_text='If set, the page will show up in the garden section of the site.', max_length=10),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='is_project',
            field=models.BooleanField(default=False, help_text='Will show up in projects section'),
        ),
        migrations.AlterField(
            model_name='series',
            name='articles',
            field=wagtail.fields.StreamField([('articles', wagtail.blocks.ListBlock(wagtail.blocks.PageChooserBlock(page_type=['home.Article'])))], blank=True, null=True, use_json_field=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='garden_status',
            field=models.CharField(choices=[('na', 'None'), ('seedling', '🌱 Seedling: For rough and early ideas'), ('budding', '🌿 Budding: For work that has been cleaned up and clarified'), ('evergreen', "🌳 Evergreen: For work that's reasonably complete, but might still receive updates.")], default='na', help_text='If set, the page will show up in the garden section of the site.', max_length=10),
        ),
        migrations.AlterField(
            model_name='series',
            name='is_project',
            field=models.BooleanField(default=False, help_text='Will show up in projects section'),
        ),
        migrations.AlterField(
            model_name='series',
            name='unlisted',
            field=models.BooleanField(default=False, help_text='If unlisted, the article will be publically accessible, and indexable by search engine, but will not show up in search, or in the list of articles on the homepage'),
        ),
    ]
