# Generated by Django 4.2 on 2024-06-26 16:52

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0083_workflowcontenttype'),
        ('home', '0012_homepage_unlisted_alter_article_garden_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagetag',
            name='content_object',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='wagtailcore.page'),
        ),
    ]
