# Generated by Django 5.0 on 2024-06-27 17:55

import django.db.models.deletion
import home.blocks
import home.oneoff_blocks
import wagtail.blocks
import wagtail.contrib.table_block.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_homepage_tags_series_tags'),
        ('wagtailcore', '0093_uploadedfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=wagtail.fields.StreamField([('text', wagtail.blocks.RichTextBlock(group='basic')), ('image', wagtail.images.blocks.ImageChooserBlock(group='basic', template='blocks/image.html')), ('table', wagtail.contrib.table_block.blocks.TableBlock(group='basic')), ('code', wagtail.blocks.StructBlock([('language', wagtail.blocks.CharBlock(required=False)), ('code', wagtail.blocks.TextBlock())], group='basic')), ('ImageDivider', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock())])), ('DescriptionBlock', wagtail.blocks.StructBlock([('text', wagtail.blocks.TextBlock())], group='basic')), ('HorizontalCardList', wagtail.blocks.StructBlock([('pages', wagtail.blocks.ListBlock(wagtail.blocks.PageChooserBlock()))], group='List')), ('GradientDescentWidget', wagtail.blocks.StructBlock([], group='oneoff')), ('StatisticalMurderWidget', home.oneoff_blocks.StatisticalMurderWidget(group='oneoff')), ('IRTWidget', home.oneoff_blocks.IRTWidget(group='oneoff')), ('WealthEnergyWidget', home.oneoff_blocks.WealthEnergyWidget(group='oneoff'))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='garden_status',
            field=models.CharField(choices=[('na', 'None'), ('seedling', '🌱 Seedling: For rough and early ideas'), ('budding', '🌿 Budding: For work that has been cleaned up and clarified'), ('evergreen', "🌳 Evergreen: For work that's reasonably complete, but might still receive updates."), ('withering', '🍂 Withering: For outdated work where inaccuracies can accumulate and my opinions may change.')], default='na', help_text='If set, the page will show up in the garden section of the site.', max_length=10),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('CardList', wagtail.blocks.StructBlock([('pages', wagtail.blocks.ListBlock(wagtail.blocks.PageChooserBlock())), ('title', wagtail.blocks.CharBlock(required=False)), ('hide_link', wagtail.blocks.BooleanBlock(default=False, required=False))], group='List')), ('HorizontalCardList', wagtail.blocks.StructBlock([('pages', wagtail.blocks.ListBlock(wagtail.blocks.PageChooserBlock()))], group='List')), ('LinesList', wagtail.blocks.StructBlock([('pages', wagtail.blocks.ListBlock(wagtail.blocks.PageChooserBlock(page_type=['home.HomePage', 'home.Article']))), ('include_images', wagtail.blocks.BooleanBlock(default=True, required=False))], group='List')), ('AboutBlurb', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(required=False)), ('tagline', wagtail.blocks.CharBlock()), ('column1_text', wagtail.blocks.RichTextBlock()), ('column2_text', wagtail.blocks.RichTextBlock()), ('page', wagtail.blocks.PageChooserBlock())], group='')), ('ContactForm', home.blocks.ContactForm(group='')), ('trending_articles', wagtail.blocks.StructBlock([('number_of_articles', wagtail.blocks.IntegerBlock(default=5, min_value=1))], group='automatic')), ('recent_articles', wagtail.blocks.StructBlock([('number_of_articles', wagtail.blocks.IntegerBlock(default=5, min_value=1))], group='automatic')), ('recent_projects', wagtail.blocks.StructBlock([('number_of_projects', wagtail.blocks.IntegerBlock(default=3, min_value=1))], group='automatic')), ('columns', wagtail.blocks.StructBlock([('columns', wagtail.blocks.StreamBlock([('column', wagtail.blocks.StructBlock([('content', wagtail.blocks.StreamBlock([('text', wagtail.blocks.RichTextBlock(group='basic')), ('image', wagtail.images.blocks.ImageChooserBlock(group='basic', template='blocks/image.html')), ('table', wagtail.contrib.table_block.blocks.TableBlock(group='basic')), ('lines_list', wagtail.blocks.StructBlock([('pages', wagtail.blocks.ListBlock(wagtail.blocks.PageChooserBlock(page_type=['home.HomePage', 'home.Article']))), ('include_images', wagtail.blocks.BooleanBlock(default=True, required=False))], group='components')), ('horizontal_card_list', wagtail.blocks.StructBlock([('pages', wagtail.blocks.ListBlock(wagtail.blocks.PageChooserBlock()))], group='components'))]))]))]))], group='layout')), ('centered', wagtail.blocks.StructBlock([('body', wagtail.blocks.StreamBlock([('text', wagtail.blocks.RichTextBlock(group='basic')), ('image', wagtail.images.blocks.ImageChooserBlock(group='basic', template='blocks/image.html')), ('table', wagtail.contrib.table_block.blocks.TableBlock(group='basic')), ('code', wagtail.blocks.StructBlock([('language', wagtail.blocks.CharBlock(required=False)), ('code', wagtail.blocks.TextBlock())], group='basic'))]))], group='layout')), ('container', wagtail.blocks.StructBlock([('content', wagtail.blocks.StreamBlock([('spacer', home.blocks.SpacerBlock(group='layout')), ('text', wagtail.blocks.RichTextBlock(group='basic')), ('image', wagtail.images.blocks.ImageChooserBlock(group='basic', template='blocks/image.html')), ('table', wagtail.contrib.table_block.blocks.TableBlock(group='basic'))]))], group='layout')), ('skipNavMargin', home.blocks.NavMarginBlock(group='spacers')), ('spacer', home.blocks.SpacerBlock(group='spacers')), ('s_spacer', home.blocks.SpacerBlock(group='spacers')), ('m_spacer', home.blocks.SpacerBlock(group='spacers')), ('l_spacer', home.blocks.SpacerBlock(group='spacers')), ('xl_spacer', home.blocks.SpacerBlock(group='spacers')), ('xxl_spacer', home.blocks.SpacerBlock(group='spacers')), ('JumbotronImageBlock', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock())], group='ImageHeader')), ('JumbotronCard', wagtail.blocks.StructBlock([('jumbotron', wagtail.blocks.PageChooserBlock())], group='ImageHeader')), ('ImageHeader', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(required=False)), ('image', wagtail.images.blocks.ImageChooserBlock()), ('large', wagtail.blocks.BooleanBlock(default=False, required=False))], group='ImageHeader')), ('ImageDivider', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock())], group='ImageHeader'))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='garden_status',
            field=models.CharField(choices=[('na', 'None'), ('seedling', '🌱 Seedling: For rough and early ideas'), ('budding', '🌿 Budding: For work that has been cleaned up and clarified'), ('evergreen', "🌳 Evergreen: For work that's reasonably complete, but might still receive updates."), ('withering', '🍂 Withering: For outdated work where inaccuracies can accumulate and my opinions may change.')], default='na', help_text='If set, the page will show up in the garden section of the site.', max_length=10),
        ),
        migrations.AlterField(
            model_name='series',
            name='garden_status',
            field=models.CharField(choices=[('na', 'None'), ('seedling', '🌱 Seedling: For rough and early ideas'), ('budding', '🌿 Budding: For work that has been cleaned up and clarified'), ('evergreen', "🌳 Evergreen: For work that's reasonably complete, but might still receive updates."), ('withering', '🍂 Withering: For outdated work where inaccuracies can accumulate and my opinions may change.')], default='na', help_text='If set, the page will show up in the garden section of the site.', max_length=10),
        ),
    ]
