# Generated by Django 5.0 on 2024-06-27 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_documentpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_type',
            field=models.CharField(choices=[('article', 'Article'), ('note', 'Note')], default='article', help_text='Type of article, e.g. Article, Note, etc.', max_length=100),
        ),
    ]
