# Generated by Django 5.0 on 2024-08-03 07:18

import django.db.models.deletion
import home.blocks
import home.oneoff_blocks
import modelcluster.contrib.taggit
import wagtail.blocks
import wagtail.contrib.table_block.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations, models

from treebeard.mp_tree import MP_Node
from taggit.models import Tag

from home.models.helper_models import HierarchicalTag

def create_new_tags(apps, schema_editor):
    # HierarchicalTag = apps.get_model('home', 'HierarchicalTag')


    # print("LKSJDF", isinstance(HierarchicalTag, MP_Node))

    for tags in Tag.objects.all().order_by('pk'):
        HierarchicalTag.add_root(name=tags.name, slug=tags.slug)

class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_article_article_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='HierarchicalTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('slug', models.SlugField(allow_unicode=True, max_length=100, unique=True, verbose_name='slug')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RunPython(create_new_tags),
    ]
