# Generated by Django 5.1 on 2025-01-12 09:20

import django.db.models.deletion
import modelcluster.contrib.taggit
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_article_starred_homepage_starred_series_starred'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentpage',
            name='garden_status',
            field=models.CharField(choices=[('na', 'None'), ('seedling', '🌱 Seedling: For rough and early ideas'), ('budding', '🌿 Budding: For work that has been cleaned up and clarified'), ('evergreen', "🌳 Evergreen: For work that's reasonably complete, but might still receive updates."), ('withering', '🍂 Withering: For outdated work where inaccuracies can accumulate and my opinions may change.')], default='na', help_text='If set, the page will show up in the garden section of the site.', max_length=10),
        ),
        migrations.AddField(
            model_name='documentpage',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='documentpage',
            name='is_project',
            field=models.BooleanField(default=False, help_text='Will show up in projects section'),
        ),
        migrations.AddField(
            model_name='documentpage',
            name='starred',
            field=models.BooleanField(default=False, help_text='If starred, a star will be displayed next to the page in the list of articles'),
        ),
        migrations.AddField(
            model_name='documentpage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='home.PageTag', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='documentpage',
            name='unlisted',
            field=models.BooleanField(default=False, help_text='If unlisted, the article will be publically accessible, and indexable by search engine, but will not show up in search, or in the list of articles on the homepage'),
        ),
        migrations.AlterField(
            model_name='article',
            name='body',
            field=wagtail.fields.StreamField([('text', 0), ('details', 2), ('image', 3), ('table', 4), ('code', 7), ('ImageDivider', 9), ('JumbotronImageBlock', 9), ('Gallery', 11), ('DescriptionBlock', 12), ('alert', 15), ('HorizontalCardList', 18), ('GradientDescentWidget', 19), ('StatisticalMurderWidget', 20), ('IRTWidget', 21), ('WealthEnergyWidget', 22)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'group': 'basic'}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('summary', 1), ('body', 1)]], {'group': 'basic'}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {'group': 'basic', 'template': 'blocks/image.html'}), 4: ('wagtail.contrib.table_block.blocks.TableBlock', (), {'group': 'basic'}), 5: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('python', 'Python'), ('javascript', 'JavaScript'), ('html', 'HTML'), ('css', 'CSS'), ('bash', 'Bash'), ('plaintext', 'Plain text')]}), 6: ('wagtail.blocks.TextBlock', (), {}), 7: ('wagtail.blocks.StructBlock', [[('language', 5), ('code', 6)]], {'group': 'basic'}), 8: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 9: ('wagtail.blocks.StructBlock', [[('image', 8)]], {}), 10: ('wagtail.blocks.ListBlock', (8,), {}), 11: ('wagtail.blocks.StructBlock', [[('images', 10)]], {}), 12: ('wagtail.blocks.StructBlock', [[('text', 6)]], {'group': 'basic'}), 13: ('wagtail.blocks.CharBlock', (), {'max_length': 2, 'required': False}), 14: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('info', 'Info'), ('warning', 'Warning'), ('danger', 'Danger'), ('success', 'Success')]}), 15: ('wagtail.blocks.StructBlock', [[('body', 1), ('icon', 13), ('style', 14)]], {'group': 'basic'}), 16: ('wagtail.blocks.PageChooserBlock', (), {}), 17: ('wagtail.blocks.ListBlock', (16,), {}), 18: ('wagtail.blocks.StructBlock', [[('pages', 17)]], {'group': 'List'}), 19: ('wagtail.blocks.StructBlock', [[]], {'group': 'oneoff'}), 20: ('home.oneoff_blocks.StatisticalMurderWidget', (), {'group': 'oneoff'}), 21: ('home.oneoff_blocks.IRTWidget', (), {'group': 'oneoff'}), 22: ('home.oneoff_blocks.WealthEnergyWidget', (), {'group': 'oneoff'})}, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('CardList', 4), ('HorizontalCardList', 5), ('LinesList', 9), ('Recommendations', 10), ('AboutBlurb', 13), ('ContactForm', 14), ('FeedBuilder', 15), ('trending_articles', 17), ('recent_articles', 17), ('recent_projects', 19), ('columns', 34), ('centered', 43), ('container', 45), ('skipNavMargin', 46), ('spacer', 47), ('s_spacer', 47), ('m_spacer', 47), ('l_spacer', 47), ('xl_spacer', 47), ('xxl_spacer', 47), ('JumbotronImageBlock', 48), ('JumbotronCard', 49), ('ImageHeader', 50), ('ImageDivider', 48)], blank=True, block_lookup={0: ('wagtail.blocks.PageChooserBlock', (), {}), 1: ('wagtail.blocks.ListBlock', (0,), {}), 2: ('wagtail.blocks.CharBlock', (), {'required': False}), 3: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('pages', 1), ('title', 2), ('hide_link', 3)]], {'group': 'List'}), 5: ('wagtail.blocks.StructBlock', [[('pages', 1)]], {'group': 'List'}), 6: ('wagtail.blocks.PageChooserBlock', (), {'page_type': ['home.HomePage', 'home.Article']}), 7: ('wagtail.blocks.ListBlock', (6,), {}), 8: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'required': False}), 9: ('wagtail.blocks.StructBlock', [[('pages', 7), ('include_images', 8)]], {'group': 'List'}), 10: ('wagtail.blocks.StructBlock', [[('title', 2)]], {'group': 'List'}), 11: ('wagtail.blocks.CharBlock', (), {}), 12: ('wagtail.blocks.RichTextBlock', (), {}), 13: ('wagtail.blocks.StructBlock', [[('title', 2), ('tagline', 11), ('column1_text', 12), ('column2_text', 12), ('page', 0)]], {'group': ''}), 14: ('home.blocks.ContactForm', (), {'group': ''}), 15: ('wagtail.blocks.StructBlock', [[]], {'group': ''}), 16: ('wagtail.blocks.IntegerBlock', (), {'default': 5, 'min_value': 1}), 17: ('wagtail.blocks.StructBlock', [[('number_of_articles', 16)]], {'group': 'automatic'}), 18: ('wagtail.blocks.IntegerBlock', (), {'default': 3, 'min_value': 1}), 19: ('wagtail.blocks.StructBlock', [[('number_of_projects', 18)]], {'group': 'automatic'}), 20: ('home.blocks.SpacerBlock', (), {'group': 'layout'}), 21: ('wagtail.blocks.RichTextBlock', (), {'group': 'basic'}), 22: ('wagtail.blocks.StructBlock', [[('summary', 12), ('body', 12)]], {'group': 'basic'}), 23: ('wagtail.images.blocks.ImageChooserBlock', (), {'group': 'basic', 'template': 'blocks/image.html'}), 24: ('wagtail.contrib.table_block.blocks.TableBlock', (), {'group': 'basic'}), 25: ('wagtail.blocks.StructBlock', [[('title', 11)]], {'group': 'section'}), 26: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 27: ('wagtail.blocks.ListBlock', (26,), {}), 28: ('wagtail.blocks.StructBlock', [[('images', 27)]], {'group': 'section'}), 29: ('wagtail.blocks.StructBlock', [[('pages', 7), ('include_images', 8)]], {'group': 'components'}), 30: ('wagtail.blocks.StructBlock', [[('pages', 1)]], {'group': 'components'}), 31: ('wagtail.blocks.StreamBlock', [[('spacer', 20), ('text', 21), ('details', 22), ('image', 23), ('table', 24), ('section_header', 25), ('gallery', 28), ('lines_list', 29), ('horizontal_card_list', 30)]], {}), 32: ('wagtail.blocks.StructBlock', [[('content', 31)]], {}), 33: ('wagtail.blocks.StreamBlock', [[('column', 32)]], {}), 34: ('wagtail.blocks.StructBlock', [[('columns', 33)]], {'group': 'layout'}), 35: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('python', 'Python'), ('javascript', 'JavaScript'), ('html', 'HTML'), ('css', 'CSS'), ('bash', 'Bash'), ('plaintext', 'Plain text')]}), 36: ('wagtail.blocks.TextBlock', (), {}), 37: ('wagtail.blocks.StructBlock', [[('language', 35), ('code', 36)]], {'group': 'basic'}), 38: ('wagtail.blocks.CharBlock', (), {'max_length': 2, 'required': False}), 39: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('info', 'Info'), ('warning', 'Warning'), ('danger', 'Danger'), ('success', 'Success')]}), 40: ('wagtail.blocks.StructBlock', [[('body', 12), ('icon', 38), ('style', 39)]], {'group': 'basic'}), 41: ('wagtail.blocks.StructBlock', [[('images', 27)]], {}), 42: ('wagtail.blocks.StreamBlock', [[('text', 21), ('details', 22), ('image', 23), ('table', 24), ('code', 37), ('alert', 40), ('section_header', 25), ('gallery', 41)]], {}), 43: ('wagtail.blocks.StructBlock', [[('body', 42)]], {'group': 'layout'}), 44: ('wagtail.blocks.StreamBlock', [[('spacer', 20), ('text', 21), ('details', 22), ('image', 23), ('table', 24), ('gallery', 28), ('section_header', 25)]], {}), 45: ('wagtail.blocks.StructBlock', [[('content', 44)]], {'group': 'layout'}), 46: ('home.blocks.NavMarginBlock', (), {'group': 'spacers'}), 47: ('home.blocks.SpacerBlock', (), {'group': 'spacers'}), 48: ('wagtail.blocks.StructBlock', [[('image', 26)]], {'group': 'ImageHeader'}), 49: ('wagtail.blocks.StructBlock', [[('jumbotron', 0)]], {'group': 'ImageHeader'}), 50: ('wagtail.blocks.StructBlock', [[('title', 2), ('image', 26), ('large', 3)]], {'group': 'ImageHeader'})}, null=True),
        ),
    ]
