# Generated by Django 5.0 on 2024-08-03 09:33

from django.db import migrations, models

from home.models.helper_models import HierarchicalTag
def fix_tree(apps, schema_editor):
    HierarchicalTag.fix_tree()

class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_alter_article_article_type_alter_article_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hierarchicaltag',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.RunPython(fix_tree),
    ]
